import type { Metadata } from "next";
import './globals.css';
import { colors, CssBaseline } from "@mui/material";
import { GlobalStyles } from "@mui/material";
import MenuBar from "./Components/menubar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const myGlobalStyles = <GlobalStyles styles={
  {
    body: {backgroundColor: '#9D6381'},
    h3: { color: '#0F110C' },
    h6: { color: '#867F7E' }
  }
} />;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {myGlobalStyles}
      <body>
        {children}
      </body>
    </html>
  );
}